import { EQUIPMENT_CATALOG, type EquipmentCategory, type EquipmentRarity } from "../profile/equipmentCatalog";
import { SHIP_CLASSES, type ShipClassId } from "../ships/classes";
import { SUPPORTED_GAME_LOCALES, type GameLocale } from "./gameLocale";

type Row = readonly [string, string, string, string, string, string, string];
type EquipmentId = `${EquipmentCategory}-${EquipmentRarity}`;
export interface EquipmentLocalization { modelName: string; name: string; origin: string; description: string }
export interface ShipClassLocalization { historicalArmament: string }
export type EquipmentLocalizationCatalog = Record<GameLocale, Record<EquipmentId, EquipmentLocalization>>;
export type ShipClassLocalizationCatalog = Record<GameLocale, Record<ShipClassId, ShipClassLocalization>>;

// Only these formal designations may be shared unchanged across locales. Descriptive
// names, origins and prose are independently localized. Internal systems without a
// historical model number use their documented manufacturer/class designation.
export const EQUIPMENT_MODEL_NAMES = {
  "mainGun-common": "QF 4.7 in Mk IX / CP Mk XVIII",
  "mainGun-purple": "Type 3 12.7 cm/50 / Type C",
  "mainGun-gold": "5 in/38 Mk 12 / Mk 38",
  "mainGun-redGold": "QF 4.5 in Mk III / RP10 Mk IV",
  "torpedo-common": "21 in Mk IX", "torpedo-purple": "G7a T1", "torpedo-gold": "Mk 15 Mod 3", "torpedo-redGold": "Type 93 Mod 3",
  "antiAir-common": "20 mm Oerlikon Mk II", "antiAir-purple": "QF 2-pdr Mk VIII", "antiAir-gold": "40 mm Bofors Mk I", "antiAir-redGold": "40 mm Bofors Mk 2 / Mk 51",
  "sideGun-common": "10.5 cm SK C/33", "sideGun-purple": "QF 5.25 in Mk I", "sideGun-gold": "15 cm SK C/28", "sideGun-redGold": "6 in/47 Mk 16",
  "depthCharge-common": "Mk VII", "depthCharge-purple": "Type 95", "depthCharge-gold": "Mk 6 / K-gun", "depthCharge-redGold": "Hedgehog Mk 10",
  "magazine-common": "Mk IX QF", "magazine-purple": "SK C/34", "magazine-gold": "Mk 38", "magazine-redGold": "",
  "engine-common": "Parsons", "engine-purple": "Kampon", "engine-gold": "General Electric", "engine-redGold": "Wagner / Deschimag",
  "steering-common": "J/K/N", "steering-purple": "Kagerō", "steering-gold": "Fletcher", "steering-redGold": "Gearing",
} as const satisfies Record<EquipmentId, string>;
export const HISTORICAL_MODEL_NAME_ALLOWLIST: ReadonlySet<string> = new Set(Object.values(EQUIPMENT_MODEL_NAMES).filter(Boolean));

const NAMES = {
  singleGun: ["单装速射炮", "單裝速射炮", "single quick-firing gun", "単装速射砲", "cañón único de tiro rápido", "Schnellfeuer-Einzelgeschütz", "одноорудийная скорострельная установка"],
  twinGun: ["双联装主炮", "雙聯裝主炮", "twin main-gun mount", "連装主砲", "montaje principal doble", "Hauptgeschütz-Zwilling", "двухорудийная установка главного калибра"],
  torpedo: ["鱼雷", "魚雷", "torpedo", "魚雷", "torpedo", "Torpedo", "торпеда"],
  steamTorpedo: ["蒸汽瓦斯鱼雷", "蒸汽瓦斯魚雷", "steam-gas torpedo", "蒸気ガス魚雷", "torpedo de vapor y gas", "Dampfgastorpedo", "парогазовая торпеда"],
  oxygenTorpedo: ["氧气鱼雷", "氧氣魚雷", "oxygen torpedo", "酸素魚雷", "torpedo de oxígeno", "Sauerstofftorpedo", "кислородная торпеда"],
  singleAA: ["单管防空炮", "單管防空炮", "single AA gun", "単装対空機関砲", "cañón antiaéreo único", "Einzel-Flak", "одноствольный зенитный автомат"],
  octupleAA: ["八联装砰砰炮", "八聯裝砰砰炮", "octuple pom-pom", "八連装ポンポン砲", "pom-pom óctuple", "Achtlings-Pom-Pom", "восьмиствольная установка «пом-пом»"],
  twinAA: ["双联装防空炮", "雙聯裝防空炮", "twin AA mount", "連装対空機関砲", "montaje antiaéreo doble", "Zwillings-Flak", "спаренный зенитный автомат"],
  quadAA: ["四联装防空炮与指挥仪", "四聯裝防空炮與指揮儀", "quad AA mount and director", "四連装対空砲・射撃指揮装置", "montaje antiaéreo cuádruple y director", "Vierlings-Flak mit Leitgerät", "счетверённый зенитный автомат с прибором управления огнём"],
  twinSecondary: ["双联装副炮", "雙聯裝副炮", "twin secondary mount", "連装副砲", "montaje secundario doble", "Sekundärgeschütz-Zwilling", "двухорудийная установка вспомогательного калибра"],
  tripleSecondary: ["三联装副炮", "三聯裝副炮", "triple secondary mount", "三連装副砲", "montaje secundario triple", "Sekundärgeschütz-Drilling", "трёхорудийная установка вспомогательного калибра"],
  sternDC: ["深水炸弹与艉轨", "深水炸彈與艉軌", "depth charges and stern racks", "爆雷・艦尾投下軌条", "cargas de profundidad y raíles de popa", "Wasserbomben mit Heckablaufschienen", "глубинные бомбы и кормовые сбрасыватели"],
  thrownDC: ["深水炸弹投射组", "深水炸彈投射組", "depth-charge thrower group", "爆雷投射機群", "grupo lanzacargas de profundidad", "Wasserbomben-Werfergruppe", "группа бомбомётов"],
  aheadASW: ["前投反潜炮", "前投反潛炮", "ahead-throwing ASW mortar", "前方投射式対潜迫撃砲", "mortero antisubmarino de lanzamiento frontal", "vorausfeuernder U-Jagd-Werfer", "носовой противолодочный бомбомёт"],
  fixedAmmo: ["定装弹处理间", "定裝彈處理間", "fixed-ammunition handling room", "固定弾薬取扱室", "cámara de manejo de munición fija", "Raum für Patronenmunition", "отделение подачи унитарных выстрелов"],
  caseHoist: ["药筒式扬弹链", "藥筒式揚彈鏈", "cased-ammunition hoist chain", "薬莢式揚弾機構", "cadena elevadora de munición con vaina", "Munitionsaufzug für Hülsentreibladungen", "цепь подачи гильзовых зарядов"],
  dualFeed: ["双路上部供弹间", "雙路上部供彈間", "dual-feed upper handling room", "二系統上部給弾室", "cámara superior de alimentación doble", "oberer Munitionsraum mit Doppelzuführung", "верхнее перегрузочное отделение с двумя линиями подачи"],
  flashProtection: ["防闪燃扬弹与水淹系统", "防閃燃揚彈與水淹系統", "flash-protected hoists and flooding system", "防炎揚弾・注水装置", "elevadores antillamarada y sistema de inundación", "flammengesicherte Aufzüge und Flutanlage", "противовспышечная подача и система затопления"],
  turbine: ["齿轮汽轮机组", "齒輪汽輪機組", "geared steam turbines", "ギヤード蒸気タービン", "turbinas de vapor con reductora", "Getriebedampfturbinen", "турбозубчатые агрегаты"],
  highPressure: ["高压锅炉与汽轮机组", "高壓鍋爐與汽輪機組", "high-pressure boilers and turbines", "高圧ボイラー・タービン", "calderas y turbinas de alta presión", "Hochdruckkessel und Turbinen", "котлы высокого давления и турбины"],
  singleRudder: ["单舵电液舵机", "單舵電液舵機", "single-rudder electrohydraulic gear", "単舵電気油圧操舵機", "servomotor electrohidráulico de timón único", "elektrohydraulische Einruderanlage", "электрогидравлическая машина одного руля"],
  dualPump: ["双泵电液舵机", "雙泵電液舵機", "dual-pump electrohydraulic steering", "二重ポンプ式電気油圧操舵機", "gobierno electrohidráulico de doble bomba", "elektrohydraulische Doppel-Pumpen-Ruderanlage", "электрогидравлический привод руля с двумя насосами"],
  dualCircuit: ["双回路电液舵机", "雙迴路電液舵機", "dual-circuit electrohydraulic steering", "二系統電気油圧操舵機", "gobierno electrohidráulico de doble circuito", "elektrohydraulische Zweikreis-Ruderanlage", "двухконтурный электрогидравлический привод руля"],
  fastSteering: ["高速电液舵机", "高速電液舵機", "high-speed electrohydraulic steering", "高速電気油圧操舵機", "gobierno electrohidráulico de alta velocidad", "elektrohydraulische Schnellruderanlage", "быстродействующий электрогидравлический привод руля"],
} as const satisfies Record<string, Row>;

const ORIGINS = {
  ukJ: ["英国 · J/K/N级驱逐舰", "英國 · J/K/N級驅逐艦", "UK · J/K/N-class destroyers", "英国 · J/K/N級駆逐艦", "Reino Unido · destructores clase J/K/N", "Großbritannien · Zerstörer der J/K/N-Klasse", "Великобритания · эсминцы типов J/K/N"],
  jpK: ["日本 · 阳炎级驱逐舰", "日本 · 陽炎級驅逐艦", "Japan · Kagerō-class destroyers", "日本 · 陽炎型駆逐艦", "Japón · destructores clase Kagerō", "Japan · Zerstörer der Kagerō-Klasse", "Япония · эсминцы типа «Кагэро»"],
  usSumner: ["美国 · 萨姆纳级驱逐舰", "美國 · 薩姆納級驅逐艦", "USA · Sumner-class destroyers", "米国 · サムナー級駆逐艦", "EE. UU. · destructores clase Sumner", "USA · Zerstörer der Sumner-Klasse", "США · эсминцы типа «Самнер»"],
  ukBattle: ["英国 · 战斗级驱逐舰", "英國 · 戰鬥級驅逐艦", "UK · Battle-class destroyers", "英国 · バトル級駆逐艦", "Reino Unido · destructores clase Battle", "Großbritannien · Zerstörer der Battle-Klasse", "Великобритания · эсминцы типа «Бэттл»"],
  ukFleet: ["英国 · 舰队驱逐舰", "英國 · 艦隊驅逐艦", "UK · fleet destroyers", "英国 · 艦隊駆逐艦", "Reino Unido · destructores de flota", "Großbritannien · Flottenzerstörer", "Великобритания · эскадренные миноносцы"],
  deDD: ["德国 · 1934/1936型驱逐舰", "德國 · 1934/1936型驅逐艦", "Germany · Type 1934/1936 destroyers", "ドイツ · 1934/1936型駆逐艦", "Alemania · destructores Tipo 1934/1936", "Deutschland · Zerstörer Typ 1934/1936", "Германия · эсминцы типов 1934/1936"],
  usF: ["美国 · 弗莱彻级驱逐舰", "美國 · 弗萊徹級驅逐艦", "USA · Fletcher-class destroyers", "米国 · フレッチャー級駆逐艦", "EE. UU. · destructores clase Fletcher", "USA · Zerstörer der Fletcher-Klasse", "США · эсминцы типа «Флетчер»"],
  jpFleet: ["日本 · 水雷战队", "日本 · 水雷戰隊", "Japan · torpedo squadrons", "日本 · 水雷戦隊", "Japón · escuadrones de torpederos", "Japan · Torpedogeschwader", "Япония · торпедные эскадры"],
  closeAA: ["英美海军 · 近程防空", "英美海軍 · 近程防空", "UK/US navies · close-range AA", "英米海軍 · 近接対空防御", "Armadas británica y estadounidense · defensa antiaérea cercana", "Britische und US-Marine · Nahbereichsflugabwehr", "Флоты Великобритании и США · ближняя ПВО"],
  ukAA: ["英国 · 舰队防空", "英國 · 艦隊防空", "UK · fleet air defence", "英国 · 艦隊防空", "Reino Unido · defensa antiaérea de flota", "Großbritannien · Flottenflugabwehr", "Великобритания · ПВО флота"],
  alliedAA: ["盟军舰艇 · 中近程防空", "盟軍艦艇 · 中近程防空", "Allied ships · medium/close-range AA", "連合国艦艇 · 中近距離対空防御", "Buques aliados · defensa antiaérea media y cercana", "Alliierte Schiffe · Mittel- und Nahbereichsflugabwehr", "Корабли союзников · ПВО средней и ближней дальности"],
  usRadar: ["美国 · 雷达哨戒驱逐舰", "美國 · 雷達哨戒驅逐艦", "USA · radar-picket destroyers", "米国 · レーダーピケット駆逐艦", "EE. UU. · destructores de piquete radar", "USA · Radarvorposten-Zerstörer", "США · эсминцы радиолокационного дозора"],
  deSecondary: ["德国 · 巡洋舰/战列舰副炮", "德國 · 巡洋艦/戰列艦副炮", "Germany · cruiser/battleship secondary batteries", "ドイツ · 巡洋艦・戦艦の副砲", "Alemania · baterías secundarias de cruceros y acorazados", "Deutschland · Sekundärartillerie für Kreuzer und Schlachtschiffe", "Германия · вспомогательная артиллерия крейсеров и линкоров"],
  ukKGV: ["英国 · 乔治五世级", "英國 · 喬治五世級", "UK · King George V class", "英国 · キング・ジョージ5世級", "Reino Unido · clase King George V", "Großbritannien · King-George-V-Klasse", "Великобритания · тип «Кинг Джордж V»"],
  deB: ["德国 · 俾斯麦级", "德國 · 俾斯麥級", "Germany · Bismarck class", "ドイツ · ビスマルク級", "Alemania · clase Bismarck", "Deutschland · Bismarck-Klasse", "Германия · тип «Бисмарк»"],
  usC: ["美国 · 克利夫兰级巡洋舰", "美國 · 克利夫蘭級巡洋艦", "USA · Cleveland-class cruisers", "米国 · クリーブランド級巡洋艦", "EE. UU. · cruceros clase Cleveland", "USA · Kreuzer der Cleveland-Klasse", "США · крейсеры типа «Кливленд»"],
  ukASW: ["英国 · 二战驱逐舰反潜装备", "英國 · 二戰驅逐艦反潛裝備", "UK · WWII destroyer ASW equipment", "英国 · 第二次大戦の駆逐艦対潜装備", "Reino Unido · equipo antisubmarino de destructores de la SGM", "Großbritannien · U-Jagd-Ausrüstung für Zerstörer im Zweiten Weltkrieg", "Великобритания · противолодочное вооружение эсминцев Второй мировой"],
  jpASW: ["日本 · 驱逐舰反潜装备", "日本 · 驅逐艦反潛裝備", "Japan · destroyer ASW equipment", "日本 · 駆逐艦対潜装備", "Japón · equipo antisubmarino de destructores", "Japan · U-Jagd-Ausrüstung für Zerstörer", "Япония · противолодочное вооружение эсминцев"],
  usASW: ["美国 · 舰队驱逐舰反潜装备", "美國 · 艦隊驅逐艦反潛裝備", "USA · fleet destroyer ASW equipment", "米国 · 艦隊駆逐艦対潜装備", "EE. UU. · equipo antisubmarino de destructores de flota", "USA · U-Jagd-Ausrüstung für Flottenzerstörer", "США · противолодочное вооружение эскадренных миноносцев"],
  alliedASW: ["盟军 · 战争后期反潜装备", "盟軍 · 戰爭後期反潛裝備", "Allies · late-war ASW equipment", "連合国 · 戦争後期の対潜装備", "Aliados · equipo antisubmarino de finales de la guerra", "Alliierte · U-Jagd-Ausrüstung der späten Kriegsjahre", "Союзники · противолодочное вооружение конца войны"],
  ukAmmo: ["英国 · 4.7英寸炮供弹体系", "英國 · 4.7英寸炮供彈體系", "UK · 4.7-inch gun ammunition supply", "英国 · 4.7インチ砲給弾系統", "Reino Unido · suministro de munición para cañones de 4,7 pulgadas", "Großbritannien · Munitionszuführung für 4,7-Zoll-Geschütze", "Великобритания · подача боеприпасов 4,7-дюймовых орудий"],
  deAmmo: ["德国 · 驱逐舰供弹体系", "德國 · 驅逐艦供彈體系", "Germany · destroyer ammunition supply", "ドイツ · 駆逐艦給弾系統", "Alemania · suministro de munición de destructores", "Deutschland · Munitionszuführung für Zerstörer", "Германия · подача боеприпасов на эсминцах"],
  usAmmo: ["美国 · 双联5英寸炮塔", "美國 · 雙聯5英寸炮塔", "USA · twin 5-inch turrets", "米国 · 5インチ連装砲塔", "EE. UU. · torres dobles de 5 pulgadas", "USA · 5-Zoll-Zwillingstürme", "США · двухорудийные 5-дюймовые башни"],
  usDC: ["美国 · 战争后期损管标准", "美國 · 戰爭後期損管標準", "USA · late-war damage-control standards", "米国 · 戦争後期の応急対策基準", "EE. UU. · normas de control de daños de finales de la guerra", "USA · Lecksicherungsstandards der späten Kriegsjahre", "США · нормы борьбы за живучесть конца войны"],
  deZ: ["德国 · 1936A型驱逐舰", "德國 · 1936A型驅逐艦", "Germany · Type 1936A destroyers", "ドイツ · 1936A型駆逐艦", "Alemania · destructores Tipo 1936A", "Deutschland · Zerstörer Typ 1936A", "Германия · эсминцы типа 1936A"],
  usSteer: ["美国 · 驱逐舰损管布置", "美國 · 驅逐艦損管配置", "USA · destroyer damage-control layout", "米国 · 駆逐艦の応急対策配置", "EE. UU. · distribución de control de daños de destructores", "USA · Lecksicherungsanordnung für Zerstörer", "США · компоновка систем живучести эсминцев"],
  usLate: ["美国 · 战争后期驱逐舰布置", "美國 · 戰爭後期驅逐艦配置", "USA · late-war destroyer layout", "米国 · 戦争後期の駆逐艦配置", "EE. UU. · distribución de destructores de finales de la guerra", "USA · Zerstöreranordnung der späten Kriegsjahre", "США · компоновка эсминцев конца войны"],
} as const satisfies Record<string, Row>;

interface Entry { name: keyof typeof NAMES; origin: keyof typeof ORIGINS; description: Row }
const ENTRIES = {
  "mainGun-common": { name: "singleGun", origin: "ukJ", description: ["1938年型单装速射炮与炮架组合；结构直接、重量适中，作为驱逐舰常备火炮基准。", "1938年型單裝速射炮與炮架組合；結構直接、重量適中，作為驅逐艦常備火炮基準。", "A 1938-pattern single quick-firing gun and mount: straightforward, moderately weighted baseline destroyer artillery.", "1938年型の単装速射砲と砲架。簡素な構造と適度な重量を持つ駆逐艦の標準火砲です。", "Cañón único de tiro rápido y montaje de 1938: artillería básica de destructor, sencilla y de peso moderado.", "Einzel-Schnellfeuergeschütz mit Lafette von 1938: einfache, mäßig schwere Standardartillerie für Zerstörer.", "Одноорудийная скорострельная установка образца 1938 года: простая конструкция и умеренная масса делают её базовой артиллерией эсминца."] },
  "mainGun-purple": { name: "twinGun", origin: "jpK", description: ["日本海军驱逐舰主炮系统，双联装炮塔提高单次齐射密度，但对空能力受炮架限制。", "日本海軍驅逐艦主炮系統，雙聯裝炮塔提高單次齊射密度，但對空能力受炮架限制。", "Japanese destroyer main guns. Twin turrets increase salvo density, but the mount limits anti-aircraft use.", "日本海軍の駆逐艦主砲。連装砲塔は斉射密度を高めますが、砲架により対空能力が制限されます。", "Artillería principal de destructor japonés. Las torres dobles concentran la salva, pero el montaje limita su uso antiaéreo.", "Japanische Zerstörerhauptartillerie. Zwillingstürme verdichten die Salve; die Lafette begrenzt den Flugabwehreinsatz.", "Главный калибр японских эсминцев. Двухорудийные башни усиливают залп, но конструкция установки ограничивает зенитный огонь."] },
  "mainGun-gold": { name: "twinGun", origin: "usSumner", description: ["二战美制双用途主炮与双联炮座，兼顾射速、装填组织和高低射界。", "二戰美製雙用途主炮與雙聯炮座，兼顧射速、裝填組織和高低射界。", "US WWII dual-purpose guns in a twin mount, balancing rate of fire, ammunition handling and elevation coverage.", "第二次大戦の米国製両用砲と連装砲架。発射速度、給弾作業、上下射界の均衡に優れます。", "Cañones estadounidenses de doble propósito en montaje doble, equilibrando cadencia, manejo de munición y elevación.", "US-Mehrzweckgeschütze des Zweiten Weltkriegs in Zwillingslafette mit ausgewogener Kadenz, Munitionszuführung und Höhenrichtung.", "Американские универсальные орудия Второй мировой в спаренной установке: баланс скорострельности, подачи и углов возвышения."] },
  "mainGun-redGold": { name: "twinGun", origin: "ukBattle", description: ["战争后期遥控动力双联炮架原型，强调快速跟踪、持续射击与双用途作战。", "戰爭後期遙控動力雙聯炮架原型，強調快速追蹤、持續射擊與雙用途作戰。", "Based on a late-war remotely powered twin mount, emphasizing rapid tracking, sustained fire and dual-purpose combat.", "戦争後期の遠隔動力連装砲架を参考に、素早い追尾、持続射撃、対水上・対空戦闘を重視します。", "Basado en un montaje doble motorizado de control remoto de finales de la guerra, centrado en seguimiento rápido y fuego sostenido de doble propósito.", "Nach einer ferngesteuerten Zwillingslafette der späten Kriegsjahre: schnelle Zielverfolgung, Dauerfeuer und Mehrzweckeinsatz.", "Основана на дистанционно управляемой спаренной установке конца войны: быстрое сопровождение, длительный огонь и универсальное применение."] },
  "torpedo-common": { name: "torpedo", origin: "ukFleet", description: ["英国水面舰常用21英寸鱼雷，以均衡射程和装药作为基础水面打击方案。", "英國水面艦常用21英寸魚雷，以均衡射程和裝藥作為基礎水面打擊方案。", "A common British 21-inch surface-launched torpedo with balanced range and warhead as a basic anti-ship option.", "英国水上艦で広く使われた21インチ魚雷。航走距離と炸薬量が均衡した基本的な対艦装備です。", "Torpedo británico habitual de 21 pulgadas, con alcance y carga equilibrados para ataque básico contra buques.", "Verbreiteter britischer 21-Zoll-Überwassertorpedo mit ausgewogener Reichweite und Sprengladung als grundlegende Seezielwaffe.", "Распространённая британская 21-дюймовая торпеда надводного пуска со сбалансированными дальностью и зарядом."] },
  "torpedo-purple": { name: "steamTorpedo", origin: "deDD", description: ["可选航速与航程的德制533毫米鱼雷；尾迹较明显，但战术设定灵活。", "可選航速與航程的德製533毫米魚雷；尾跡較明顯，但戰術設定靈活。", "A German 533 mm torpedo with selectable speed and range. Its visible wake trades concealment for flexible settings.", "速度と航走距離を選べるドイツ製533 mm魚雷。航跡は目立ちますが、戦術設定に柔軟性があります。", "Torpedo alemán de 533 mm con velocidad y alcance seleccionables. Su estela es visible, pero ofrece ajustes tácticos flexibles.", "Deutscher 533-mm-Torpedo mit wählbarer Geschwindigkeit und Reichweite; auffällige Blasenspur, aber flexible taktische Einstellungen.", "Немецкая 533-мм торпеда с выбором скорости и дальности. Заметный след компенсируется гибкостью настроек."] },
  "torpedo-gold": { name: "torpedo", origin: "usF", description: ["美国海军二战驱逐舰标准水面发射鱼雷，使用五联装发射器形成集中雷击。", "美國海軍二戰驅逐艦標準水面發射魚雷，使用五聯裝發射器形成集中雷擊。", "The US Navy's standard WWII destroyer surface-launched torpedo, fired from quintuple tubes for concentrated attacks.", "第二次大戦の米海軍駆逐艦の標準水上発射魚雷。五連装発射管で集中雷撃を行います。", "Torpedo estándar de lanzamiento en superficie de destructores estadounidenses de la SGM, usado en tubos quíntuples para ataques concentrados.", "Standard-Überwassertorpedo der US-Zerstörer im Zweiten Weltkrieg; Fünffachrohrsätze ermöglichen konzentrierte Angriffe.", "Стандартная торпеда надводного пуска американских эсминцев Второй мировой; пятитрубные аппараты обеспечивают плотный залп."] },
  "torpedo-redGold": { name: "oxygenTorpedo", origin: "jpFleet", description: ["以氧气推进换取远射程与大装药的610毫米鱼雷，威力突出但舰上储存风险更高。", "以氧氣推進換取遠射程與大裝藥的610毫米魚雷，威力突出但艦上儲存風險更高。", "A 610 mm oxygen torpedo with long range and a large warhead. Powerful, but riskier to store aboard ship.", "酸素推進による長射程と大炸薬量を持つ610 mm魚雷。強力ですが、艦内保管の危険性が高くなります。", "Torpedo de oxígeno de 610 mm con gran alcance y carga. Potente, pero con mayor riesgo de almacenamiento a bordo.", "610-mm-Sauerstofftorpedo mit großer Reichweite und Sprengladung; sehr wirksam, aber riskanter an Bord zu lagern.", "610-мм кислородная торпеда с большой дальностью и мощным зарядом. Высокая эффективность сочетается с повышенным риском хранения."] },
  "antiAir-common": { name: "singleAA", origin: "closeAA", description: ["二战舰艇广泛使用的单管近程机关炮，轻便可靠，适合填补近距离射界。", "二戰艦艇廣泛使用的單管近程機關炮，輕便可靠，適合填補近距離射界。", "A widely used WWII single-barrel close-range autocannon: light, reliable and useful for covering nearby firing arcs.", "第二次大戦の艦艇で広く使われた単装近接機関砲。軽量で信頼性が高く、近距離射界を補います。", "Cañón automático único muy usado en la SGM: ligero, fiable y útil para cubrir sectores cercanos.", "Weit verbreitete einläufige Nahbereichs-Maschinenkanone des Zweiten Weltkriegs: leicht, zuverlässig und geeignet, nahe Feuersektoren abzudecken.", "Широко применявшийся во Второй мировой одноствольный автомат ближнего действия: лёгкий и надёжный, закрывает ближние сектора огня."] },
  "antiAir-purple": { name: "octupleAA", origin: "ukAA", description: ["多管齐射形成密集弹幕，适合舰队近程防空，但整套炮座体积较大。", "多管齊射形成密集彈幕，適合艦隊近程防空，但整套炮座體積較大。", "Multiple barrels create a dense barrage for close fleet air defence, at the cost of a bulky mounting.", "多砲身の斉射で近接防空用の密な弾幕を形成しますが、砲座は大型です。", "Varios tubos crean una barrera densa para defensa antiaérea cercana de flota, a costa de un montaje voluminoso.", "Mehrere Rohre erzeugen dichtes Sperrfeuer zur Flottennahverteidigung; die Lafette benötigt viel Platz.", "Несколько стволов создают плотную завесу ближней ПВО флота, но установка занимает много места."] },
  "antiAir-gold": { name: "twinAA", origin: "alliedAA", description: ["战争中后期广泛采用的40毫米自动炮，射程、威力和持续射击能力均衡。", "戰爭中後期廣泛採用的40毫米自動炮，射程、威力和持續射擊能力均衡。", "A 40 mm automatic gun widely adopted in the middle and late war, balancing range, power and sustained fire.", "戦争中後期に広く採用された40 mm機関砲。射程、威力、持続射撃能力が均衡しています。", "Cañón automático de 40 mm ampliamente adoptado desde mediados de la guerra, con alcance, potencia y fuego sostenido equilibrados.", "Ab der Kriegsmitte weit verbreitete 40-mm-Maschinenkanone mit ausgewogener Reichweite, Wirkung und Dauerfeuerleistung.", "40-мм автомат, широко применявшийся в середине и конце войны; сбалансированы дальность, мощность и длительность огня."] },
  "antiAir-redGold": { name: "quadAA", origin: "usRadar", description: ["四联装博福斯炮配合Mk 51指挥仪的原型组合，强化集中火力和目标跟踪。", "四聯裝博福斯炮配合Mk 51指揮儀的原型組合，強化集中火力和目標追蹤。", "Based on quad Bofors guns paired with the Mk 51 director, improving concentrated fire and target tracking.", "四連装ボフォース砲とMk 51射撃指揮装置を参考にした組み合わせ。火力集中と目標追尾を強化します。", "Basado en Bofors cuádruples con director Mk 51, para mejorar la concentración de fuego y el seguimiento.", "Nach Vierlings-Bofors mit Mk-51-Leitgerät: bessere Feuerkonzentration und Zielverfolgung.", "Сочетание счетверённых «Бофорсов» с прибором Mk 51 усиливает сосредоточенный огонь и сопровождение цели."] },
  "sideGun-common": { name: "twinSecondary", origin: "deSecondary", description: ["德制双用途副炮，适合大型舰艇舷侧与上层建筑周边的中程防御。", "德製雙用途副炮，適合大型艦艇舷側與上層建築周邊的中程防禦。", "German dual-purpose secondary guns for medium-range defence along the sides and superstructures of larger ships.", "大型艦の舷側や上部構造周辺の中距離防御に適したドイツ製両用副砲。", "Cañones secundarios alemanes de doble propósito para defensa a media distancia en los costados y superestructuras de buques grandes.", "Deutsche Mehrzweck-Sekundärgeschütze zur Verteidigung mittlerer Reichweite an Bordseiten und Aufbauten großer Schiffe.", "Немецкие универсальные вспомогательные орудия для обороны бортов и надстроек крупных кораблей на средней дальности."] },
  "sideGun-purple": { name: "twinSecondary", origin: "ukKGV", description: ["兼顾对海和对空的英制双用途副炮；炮弹较重，对装填组织要求较高。", "兼顧對海和對空的英製雙用途副炮；炮彈較重，對裝填組織要求較高。", "British dual-purpose secondary guns for surface and air targets. Heavy shells require well-organized loading.", "対水上・対空を兼ねる英国製両用副砲。砲弾が重く、給弾作業の効率が求められます。", "Cañones secundarios británicos de doble propósito. Sus proyectiles pesados exigen una recarga bien organizada.", "Britische Mehrzweck-Sekundärgeschütze gegen See- und Luftziele. Schwere Granaten stellen hohe Anforderungen an den Ladeablauf.", "Британские универсальные вспомогательные орудия против морских и воздушных целей. Тяжёлые снаряды требуют отлаженной подачи."] },
  "sideGun-gold": { name: "twinSecondary", origin: "deB", description: ["大型舰艇中口径副炮，强调对驱逐舰与轻型目标的水面压制能力。", "大型艦艇中口徑副炮，強調對驅逐艦與輕型目標的水面壓制能力。", "Medium-calibre secondary guns for large ships, emphasizing surface suppression of destroyers and light targets.", "大型艦用の中口径副砲。駆逐艦や軽量目標への対水上制圧を重視します。", "Artillería secundaria de calibre medio para buques grandes, centrada en suprimir destructores y blancos ligeros.", "Mittelkalibrige Sekundärgeschütze großer Schiffe, ausgelegt zur Bekämpfung von Zerstörern und leichten Seezielen.", "Среднекалиберная вспомогательная артиллерия крупных кораблей для подавления эсминцев и лёгких надводных целей."] },
  "sideGun-redGold": { name: "tripleSecondary", origin: "usC", description: ["美制轻巡洋舰三联主炮系统，在大型舰体上提供高射速与密集舷侧火力。", "美製輕巡洋艦三聯主炮系統，在大型艦體上提供高射速與密集舷側火力。", "A US light-cruiser triple main-gun system used on large hulls for rapid fire and dense broadsides.", "米国軽巡洋艦の三連装主砲系統。大型艦体では高い発射速度と密な舷側火力を発揮します。", "Sistema principal triple de crucero ligero estadounidense que proporciona gran cadencia y andanadas densas en cascos grandes.", "US-Drillingstürme leichter Kreuzer liefern auf großen Rümpfen hohe Kadenz und dichte Breitseiten.", "Американская трёхорудийная система главного калибра лёгких крейсеров обеспечивает на крупных корпусах высокую скорострельность и плотный бортовой залп."] },
  "depthCharge-common": { name: "sternDC", origin: "ukASW", description: ["舰艉投放轨与基础定深深水炸弹，已可在海试模式对水下训练靶使用。", "艦艉投放軌與基礎定深深水炸彈，已可在海試模式對水下訓練靶使用。", "Stern racks and basic depth-set charges, usable against submerged training targets in sea trials.", "艦尾投下軌条と基本的な設定深度爆雷。海上試験の水中訓練標的に使用できます。", "Raíles de popa y cargas de profundidad básicas ajustables, utilizables contra blancos de entrenamiento sumergidos en pruebas de mar.", "Heckablaufschienen mit einfachen tiefeneingestellten Wasserbomben, bei Probefahrten gegen Unterwasser-Übungsziele einsetzbar.", "Кормовые сбрасыватели и простые бомбы с заданной глубиной подрыва; доступны против подводных учебных целей в морских испытаниях."] },
  "depthCharge-purple": { name: "thrownDC", origin: "jpASW", description: ["以投射机扩大覆盖宽度的反潜配置；首版沿用标准深弹参数，专属阵型待后续接入。", "以投射機擴大覆蓋寬度的反潛配置；首版沿用標準深彈參數，專屬陣型待後續接入。", "Throwers widen the ASW coverage. This version uses standard depth-charge parameters; dedicated patterns are not implemented yet.", "投射機で対潜攻撃の幅を広げる装備。現版では標準爆雷の性能を使用し、専用散布パターンは未実装です。", "Los lanzadores amplían la cobertura antisubmarina. Esta versión usa parámetros estándar; los patrones propios aún no están implementados.", "Werfer verbreitern die U-Jagd-Abdeckung. Diese Version nutzt Standard-Wasserbombenwerte; eigene Wurfmuster sind noch nicht umgesetzt.", "Бомбомёты расширяют полосу противолодочного удара. Пока используются стандартные параметры глубинных бомб; особая схема залпа ещё не реализована."] },
  "depthCharge-gold": { name: "thrownDC", origin: "usASW", description: ["由舷侧 K-gun 与艉轨形成连续投放阵列；首版沿用标准深弹参数，专属阵型待后续接入。", "由舷側 K-gun 與艉軌形成連續投放陣列；首版沿用標準深彈參數，專屬陣型待後續接入。", "Side K-guns and stern racks form a continuous release array. Standard depth-charge parameters are used; dedicated patterns are not implemented yet.", "舷側K-gunと艦尾軌条による連続投下装備。標準爆雷の性能を使用し、専用散布パターンは未実装です。", "K-guns laterales y raíles de popa forman una secuencia continua. Se usan parámetros estándar; los patrones propios aún no están implementados.", "Seitliche K-guns und Heckschienen bilden eine fortlaufende Abwurfanordnung. Standardwerte gelten; eigene Wurfmuster sind noch nicht umgesetzt.", "Бортовые K-gun и кормовые сбрасыватели обеспечивают последовательную постановку. Пока действуют стандартные параметры; особая схема залпа ещё не реализована."] },
  "depthCharge-redGold": { name: "aheadASW", origin: "alliedASW", description: ["保持声呐接触时向舰首前方投射弹幕；前投接触引信逻辑尚未接入，首版沿用标准深弹参数。", "保持聲納接觸時向艦首前方投射彈幕；前投接觸引信邏輯尚未接入，首版沿用標準深彈參數。", "Designed to fire ahead while maintaining sonar contact. Ahead-throwing contact-fuze logic is not implemented; this version uses standard depth-charge parameters.", "ソナー接触を保ちつつ艦首前方へ投射する装備。前方投射・接触信管の挙動は未実装で、現版は標準爆雷の性能を使用します。", "Diseñado para disparar hacia proa manteniendo el contacto sonar. El lanzamiento frontal y la espoleta de contacto aún no están implementados; usa parámetros estándar.", "Für Vorausfeuer bei gehaltenem Sonarkontakt vorgesehen. Vorauswurf und Aufschlagzünder sind noch nicht umgesetzt; diese Version nutzt Standard-Wasserbombenwerte.", "Предназначен для стрельбы вперёд с сохранением гидроакустического контакта. Передний залп и контактный взрыватель ещё не реализованы; используются стандартные параметры глубинных бомб."] },
  "magazine-common": { name: "fixedAmmo", origin: "ukAmmo", description: ["参考英制速射炮弹药处理间和扬弹路线，维护简单，装填提升有限。", "參考英製速射炮彈藥處理間和揚彈路線，維護簡單，裝填提升有限。", "Based on British quick-firing gun handling rooms and hoist routes: simple maintenance with a modest reload improvement.", "英国速射砲の弾薬取扱室と揚弾経路を参考にした装備。整備は簡単ですが装填改善は小幅です。", "Basado en cámaras y rutas elevadoras británicas de tiro rápido: mantenimiento sencillo y mejora modesta de recarga.", "Nach britischen Munitionsräumen und Aufzügen für Schnellfeuergeschütze: wartungsarm mit mäßiger Ladeverbesserung.", "На основе британских отделений подачи скорострельных орудий: простое обслуживание и небольшое ускорение заряжания."] },
  "magazine-purple": { name: "caseHoist", origin: "deAmmo", description: ["参考德制药筒式弹药与分层输送布置，缩短炮塔内的下一发准备时间。", "參考德製藥筒式彈藥與分層輸送配置，縮短炮塔內的下一發準備時間。", "Based on German cased ammunition and staged transfer arrangements, reducing preparation time for the next round in the turret.", "ドイツの薬莢式弾薬と段階輸送配置を参考に、砲塔内で次弾を準備する時間を短縮します。", "Basado en munición alemana con vaina y transporte por etapas, reduce el tiempo de preparación del siguiente disparo en la torre.", "Nach deutscher Hülsenmunition und gestaffelter Zuführung; verkürzt die Vorbereitung der nächsten Granate im Turm.", "На основе немецкой гильзовой системы и многоступенчатой подачи; сокращает подготовку следующего выстрела в башне."] },
  "magazine-gold": { name: "dualFeed", origin: "usAmmo", description: ["参考Mk 38双联炮座上部供弹间，为两根炮管维持更稳定的连续装填节奏。", "參考Mk 38雙聯炮座上部供彈間，為兩根炮管維持更穩定的連續裝填節奏。", "Based on the Mk 38 twin mount's upper handling room, sustaining a steadier continuous loading rhythm for both barrels.", "Mk 38連装砲架の上部給弾室を参考に、両砲身の連続装填をより安定させます。", "Basado en la cámara superior del montaje doble Mk 38, mantiene un ritmo de carga más estable para ambos tubos.", "Nach dem oberen Munitionsraum der Mk-38-Zwillingslafette; stabilisiert den kontinuierlichen Ladeablauf beider Rohre.", "На основе верхнего перегрузочного отделения спаренной установки Mk 38; поддерживает более устойчивый темп подачи к обоим стволам."] },
  "magazine-redGold": { name: "flashProtection", origin: "usDC", description: ["以防闪燃隔离、扬弹路线和弹药库水淹能力为原型；装填组织更强，但储弹密度提高风险。", "以防閃燃隔離、揚彈路線和彈藥庫水淹能力為原型；裝填組織更強，但儲彈密度提高風險。", "Based on flash isolation, ammunition hoists and magazine flooding. Better handling, but denser ammunition storage increases risk.", "防炎隔離、揚弾経路、弾薬庫注水を参考にした装備。給弾効率は上がりますが、高密度保管で危険性が増します。", "Basado en aislamiento antillamarada, elevadores e inundación de pañoles. Mejora el manejo, pero almacenar más munición aumenta el riesgo.", "Nach Flammensperren, Munitionsaufzügen und Magazinflutung. Besserer Ladeablauf, jedoch erhöht dichtere Lagerung das Risiko.", "На основе противовспышечной изоляции, подачи и затопления погреба. Подача лучше, но плотное хранение боезапаса повышает риск."] },
  "engine-common": { name: "turbine", origin: "ukJ", description: ["参考英国舰队驱逐舰的齿轮汽轮机布置，输出平稳、维护体系成熟。", "參考英國艦隊驅逐艦的齒輪汽輪機配置，輸出平穩、維護體系成熟。", "Based on British fleet-destroyer geared turbines, with steady output and established maintenance practices.", "英国艦隊駆逐艦のギヤードタービン配置を参考に、安定した出力と成熟した整備体系を備えます。", "Basado en turbinas con reductora de destructores británicos, con potencia estable y mantenimiento consolidado.", "Nach britischen Flottenzerstörer-Getriebeturbinen mit gleichmäßiger Leistung und bewährter Wartung.", "На основе турбозубчатой установки британских эсминцев: ровная мощность и отработанная система обслуживания."] },
  "engine-purple": { name: "turbine", origin: "jpK", description: ["参考日本海军阳炎级动力布置，在续航、舰体空间和高速输出之间取平衡。", "參考日本海軍陽炎級動力配置，在續航、艦體空間和高速輸出之間取平衡。", "Based on Kagerō-class machinery, balancing endurance, hull space and high-speed power.", "日本海軍陽炎型の機関配置を参考に、航続力、船内空間、高速出力の均衡を図ります。", "Basado en la maquinaria de la clase Kagerō, equilibra autonomía, espacio interior y potencia a alta velocidad.", "Nach der Maschinenanlage der Kagerō-Klasse: Ausgleich zwischen Ausdauer, Rumpfraum und Hochgeschwindigkeitsleistung.", "На основе энергетической установки типа «Кагэро»: баланс дальности плавания, объёма корпуса и мощности на полном ходу."] },
  "engine-gold": { name: "turbine", origin: "usF", description: ["参考弗莱彻级双轴动力系统，强调可靠的大功率输出和战时损管冗余。", "參考弗萊徹級雙軸動力系統，強調可靠的大功率輸出和戰時損管備援。", "Based on Fletcher-class twin-shaft machinery, emphasizing reliable high output and wartime damage-control redundancy.", "フレッチャー級の二軸機関を参考に、信頼性の高い大出力と戦時応急対策の冗長性を重視します。", "Basado en la maquinaria de dos ejes de la clase Fletcher, prioriza alta potencia fiable y redundancia para control de daños.", "Nach der Zweiwellenanlage der Fletcher-Klasse mit Schwerpunkt auf zuverlässiger hoher Leistung und Redundanz bei Gefechtsschäden.", "На основе двухвальной установки типа «Флетчер»: надёжная высокая мощность и резервирование для борьбы за живучесть."] },
  "engine-redGold": { name: "highPressure", origin: "deZ", description: ["参考德制高压蒸汽动力系统，以复杂维护换取高输出；游戏中作为舰队试验动力。", "參考德製高壓蒸汽動力系統，以複雜維護換取高輸出；遊戲中作為艦隊試驗動力。", "Based on German high-pressure steam machinery: high output with complex maintenance, represented as experimental fleet machinery in game.", "ドイツの高圧蒸気機関を参考に、複雑な整備と引き換えに高出力を得ます。ゲームでは艦隊試験用機関です。", "Basado en maquinaria alemana de vapor a alta presión: gran potencia y mantenimiento complejo, representada como maquinaria experimental de flota.", "Nach deutscher Hochdruckdampftechnik: hohe Leistung bei komplexer Wartung; im Spiel als Flottenerprobungsantrieb dargestellt.", "На основе немецкой паросиловой установки высокого давления: высокая мощность ценой сложного обслуживания; в игре это опытная флотская установка."] },
  "steering-common": { name: "singleRudder", origin: "ukFleet", description: ["参考英国驱逐舰单舵与电液操舵系统，响应可预测，适合作为基础转向机构。", "參考英國驅逐艦單舵與電液操舵系統，反應可預測，適合作為基礎轉向機構。", "Based on British destroyer single-rudder electrohydraulic systems, with predictable response as baseline steering gear.", "英国駆逐艦の単舵・電気油圧操舵を参考に、予測しやすい応答を持つ基本操舵装置です。", "Basado en sistemas británicos electrohidráulicos de timón único, con respuesta predecible como mecanismo básico de gobierno.", "Nach britischer elektrohydraulischer Einrudersteuerung für Zerstörer; berechenbare Reaktion als grundlegende Ruderanlage.", "На основе британского электрогидравлического привода одного руля: предсказуемая реакция базовой рулевой машины."] },
  "steering-purple": { name: "dualPump", origin: "jpFleet", description: ["参考阳炎级操舵动力与泵组冗余，改善持续转舵时的响应稳定性。", "參考陽炎級操舵動力與泵組備援，改善持續轉舵時的反應穩定性。", "Based on Kagerō-class steering power and redundant pumps, improving response stability during sustained rudder movement.", "陽炎型の操舵動力とポンプ冗長性を参考に、持続的な転舵中の応答を安定させます。", "Basado en la potencia de gobierno y bombas redundantes de la clase Kagerō, estabiliza la respuesta durante giros sostenidos.", "Nach Ruderantrieb und redundanten Pumpen der Kagerō-Klasse; stabilere Reaktion bei anhaltender Ruderbewegung.", "На основе привода руля и резервных насосов типа «Кагэро»; улучшает устойчивость реакции при длительной перекладке."] },
  "steering-gold": { name: "dualCircuit", origin: "usSteer", description: ["参考弗莱彻级分舱和冗余操舵思路，提高战损环境下的转向响应。", "參考弗萊徹級分艙和備援操舵設計，提高戰損環境下的轉向反應。", "Based on Fletcher-class compartmentation and redundant steering, improving steering response under battle damage.", "フレッチャー級の区画分離と操舵冗長性を参考に、戦闘損傷下の操舵応答を改善します。", "Basado en compartimentación y gobierno redundante de la clase Fletcher, mejora la respuesta con daños de combate.", "Nach Schottenunterteilung und redundanter Steuerung der Fletcher-Klasse; bessere Ruderreaktion unter Gefechtsschäden.", "На основе разделения на отсеки и резервного управления типа «Флетчер»; повышает отзывчивость руля при боевых повреждениях."] },
  "steering-redGold": { name: "fastSteering", origin: "usLate", description: ["参考加长型高速驱逐舰的操舵需求，强化高速航行时的舵角建立速度。", "參考加長型高速驅逐艦的操舵需求，強化高速航行時的舵角建立速度。", "Based on the steering needs of lengthened high-speed destroyers, increasing rudder-angle response at high speed.", "長船体の高速駆逐艦の操舵要求を参考に、高速航行時に舵角が付く速さを高めます。", "Basado en las necesidades de destructores rápidos alargados, acelera el establecimiento del ángulo de timón a alta velocidad.", "Nach den Steueranforderungen verlängerter schneller Zerstörer; schnellerer Ruderwinkeleinsatz bei hoher Fahrt.", "На основе требований удлинённых быстроходных эсминцев; ускоряет набор угла руля на высокой скорости."] },
} as const satisfies Record<EquipmentId, Entry>;

export const EQUIPMENT_LOCALIZATION_CATALOG = Object.fromEntries(SUPPORTED_GAME_LOCALES.map((locale, index) => [locale,
  Object.fromEntries(Object.entries(ENTRIES).map(([id, entry]) => {
    const designation = EQUIPMENT_MODEL_NAMES[id as EquipmentId];
    // No formal designation exists for the generic flash-protection system.
    const modelName = designation || NAMES[entry.name][index];
    return [id, { modelName, name: designation ? `${modelName} ${NAMES[entry.name][index]}` : modelName, origin: ORIGINS[entry.origin][index], description: entry.description[index] }];
  })),
])) as EquipmentLocalizationCatalog;

export function equipmentLocale(locale: GameLocale, id: string): EquipmentLocalization {
  const entry = EQUIPMENT_LOCALIZATION_CATALOG[locale][id as EquipmentId];
  if (!entry) throw new Error(`Missing equipment localization: ${locale}/${id}`);
  return entry;
}

// An explicit ID-set check also catches catalog additions not represented in the
// compile-time category/rarity matrix. Never fall back to Chinese for unknown IDs.
for (const item of EQUIPMENT_CATALOG) {
  if (!Object.hasOwn(ENTRIES, item.id)) throw new Error(`Unlocalized equipment: ${item.id}`);
}

const MOUNT_NAMES = {
  1: ["单装", "單裝", "single", "単装", "simple", "Einzel", "одноорудийная"],
  2: ["双联", "雙聯", "twin", "連装", "doble", "Zwilling", "двухорудийная"],
  3: ["三联", "三聯", "triple", "三連装", "triple", "Drilling", "трёхорудийная"],
  4: ["四联", "四聯", "quadruple", "四連装", "cuádruple", "Vierling", "четырёхорудийная"],
  5: ["五联", "五聯", "quintuple", "五連装", "quíntuple", "Fünfling", "пятитрубная"],
} as const satisfies Record<number, Row>;
const ARMAMENT_NOTES = {
  kGun: ["K-gun 与艉轨", "K-gun 與艉軌", "K-guns and stern racks", "K-gun・艦尾投下軌条", "K-guns y raíles de popa", "K-guns und Heckablaufschienen", "K-gun и кормовые сбрасыватели"],
  throwers: ["投射器与艉轨", "投射器與艉軌", "depth-charge throwers and stern racks", "爆雷投射機・艦尾投下軌条", "lanzacargas y raíles de popa", "Wasserbombenwerfer und Heckablaufschienen", "бомбомёты и кормовые сбрасыватели"],
  dc: ["深弹投放装置", "深彈投放裝置", "depth-charge gear", "爆雷投下装置", "equipo de cargas de profundidad", "Wasserbombenanlagen", "устройства сброса глубинных бомб"],
  noTorpedoes: ["无鱼雷", "無魚雷", "no torpedoes", "魚雷なし", "sin torpedos", "keine Torpedos", "без торпед"],
  lightAA: ["88 mm 与轻防空", "88 mm 與輕防空", "88 mm guns and light AA", "88 mm砲・軽対空砲", "cañones de 88 mm y antiaéreos ligeros", "88-mm-Geschütze und leichte Flak", "88-мм орудия и лёгкая зенитная артиллерия"],
  pomPom: ["砰砰炮", "砰砰炮", "pom-pom guns", "ポンポン砲", "cañones pom-pom", "Pom-Pom-Geschütze", "установки «пом-пом»"],
} as const satisfies Record<string, Row>;
type Mount = readonly [number, keyof typeof MOUNT_NAMES, string, "gun" | "torpedo"];
const ARMAMENT: Record<ShipClassId, { mounts: readonly Mount[]; note?: keyof typeof ARMAMENT_NOTES }> = {
  fletcher: { mounts: [[5, 1, "5 in/38 Mk 12", "gun"], [2, 5, "Mk 15", "torpedo"]], note: "kGun" },
  "j-class": { mounts: [[3, 2, "QF 4.7 in Mk XII", "gun"], [2, 5, "21 in Mk IX", "torpedo"]], note: "throwers" },
  kagero: { mounts: [[3, 2, "12.7 cm Type 3", "gun"], [2, 4, "610 mm Type 93", "torpedo"]], note: "dc" },
  "type-1936a": { mounts: [[1, 2, "15 cm", "gun"], [3, 1, "15 cm", "gun"], [2, 4, "533 mm", "torpedo"]], note: "dc" },
  tashkent: { mounts: [[3, 2, "130 mm B-2LM", "gun"], [3, 3, "533 mm", "torpedo"]], note: "throwers" },
  cleveland: { mounts: [[4, 3, "6 in/47 Mk 16", "gun"], [6, 2, "5 in/38", "gun"]], note: "noTorpedoes" },
  edinburgh: { mounts: [[4, 3, "6 in Mk XXIII", "gun"], [2, 3, "533 mm", "torpedo"], [6, 2, "4 in", "gun"]] },
  nurnberg: { mounts: [[3, 3, "15 cm SK C/25", "gun"], [4, 3, "533 mm", "torpedo"]], note: "lightAA" },
  agano: { mounts: [[3, 2, "152 mm", "gun"], [2, 4, "610 mm", "torpedo"], [2, 2, "80 mm", "gun"]] },
  dido: { mounts: [[5, 2, "5.25 in", "gun"], [2, 3, "533 mm", "torpedo"]], note: "pomPom" },
  "north-carolina": { mounts: [[3, 3, "16 in/45", "gun"], [10, 2, "5 in/38", "gun"]], note: "noTorpedoes" },
  "king-george-v": { mounts: [[2, 4, "14 in", "gun"], [1, 2, "14 in", "gun"], [8, 2, "5.25 in", "gun"]], note: "noTorpedoes" },
  bismarck: { mounts: [[4, 2, "38 cm SK C/34", "gun"], [6, 2, "15 cm", "gun"]], note: "noTorpedoes" },
  yamato: { mounts: [[3, 3, "460 mm", "gun"], [4, 3, "155 mm", "gun"]], note: "noTorpedoes" },
  richelieu: { mounts: [[2, 4, "380 mm", "gun"], [3, 3, "152 mm", "gun"]], note: "noTorpedoes" },
};
const TORPEDO_MOUNT = ["鱼雷发射器", "魚雷發射器", "torpedo launcher", "魚雷発射管", "lanzatorpedos", "Torpedorohrsatz", "торпедный аппарат"] as const;
const RUSSIAN_TORPEDO_TUBES: Record<number, string> = { 1: "однотрубный", 2: "двухтрубный", 3: "трёхтрубный", 4: "четырёхтрубный", 5: "пятитрубный" };
export const SHIP_CLASS_LOCALIZATION_CATALOG = Object.fromEntries(SUPPORTED_GAME_LOCALES.map((locale, index) => [locale,
  Object.fromEntries(Object.entries(ARMAMENT).map(([id, entry]) => [id, { historicalArmament: [
    ...entry.mounts.map(([count, barrels, model, kind]) => `${count} × ${locale === "ru-RU" && kind === "torpedo" ? RUSSIAN_TORPEDO_TUBES[barrels] : MOUNT_NAMES[barrels][index]} ${model}${kind === "torpedo" ? ` ${TORPEDO_MOUNT[index]}` : ""}`),
    ...(entry.note ? [ARMAMENT_NOTES[entry.note][index]] : []),
  ].join("; ") }])),
])) as ShipClassLocalizationCatalog;
export function shipClassLocale(locale: GameLocale, id: ShipClassId): ShipClassLocalization {
  const entry = SHIP_CLASS_LOCALIZATION_CATALOG[locale][id];
  if (!entry) throw new Error(`Missing ship armament localization: ${locale}/${id}`);
  return entry;
}
for (const id of Object.keys(SHIP_CLASSES)) {
  if (!Object.hasOwn(ARMAMENT, id)) throw new Error(`Unlocalized ship armament: ${id}`);
}
