import { SUPPORTED_GAME_LOCALES, type GameLocale } from "./gameLocale";

type Row = readonly [string, string, string, string, string, string, string];
export const LAN_MESSAGE_ROWS = {
  "search-empty": ["未发现可加入的房间。", "未發現可加入的房間。", "No available rooms found.", "参加できる部屋が見つかりません。", "No se encontraron salas disponibles.", "Keine verfügbaren Räume gefunden.", "Доступные комнаты не найдены."],
  "host-create-failed": ["创建房间失败。", "建立房間失敗。", "Could not create a room.", "部屋を作成できませんでした。", "No se pudo crear la sala.", "Raum konnte nicht erstellt werden.", "Не удалось создать комнату."],
  "manual-join-timeout": ["加入房间超时。", "加入房間逾時。", "Joining the room timed out.", "参加がタイムアウトしました。", "Se agotó el tiempo para unirse.", "Zeitüberschreitung beim Beitreten.", "Время ожидания подключения истекло."],
  "manual-join-disconnected": ["加入房间时连接断开。", "加入房間時連線中斷。", "Connection lost while joining.", "参加中に接続が切れました。", "Se perdió la conexión al unirse.", "Verbindung beim Beitreten getrennt.", "Соединение разорвано при подключении."],
  "host-disconnected": ["房主已断开。", "房主已斷線。", "The host disconnected.", "ホストが切断しました。", "El anfitrión se desconectó.", "Der Host hat die Verbindung getrennt.", "Ведущий отключился."],
  "version-mismatch": ["游戏版本不一致，无法加入。", "遊戲版本不同，無法加入。", "Game versions differ; cannot join.", "ゲームバージョンが異なるため参加できません。", "Las versiones del juego no coinciden; no puedes unirte.", "Die Spielversionen unterscheiden sich; Beitritt nicht möglich.", "Версии игры различаются; подключение невозможно."],
  "content-mismatch": ["内容哈希不一致，无法加入。", "內容雜湊不同，無法加入。", "Content hashes differ; cannot join.", "コンテンツハッシュが異なるため参加できません。", "El contenido no coincide; no puedes unirte.", "Die Inhalts-Hashes unterscheiden sich; Beitritt nicht möglich.", "Хеши содержимого различаются; подключение невозможно."],
  "room-full": ["房间已满。", "房間已滿。", "The room is full.", "部屋が満員です。", "La sala está llena.", "Der Raum ist voll.", "Комната заполнена."],
  "invalid-build": ["当前方案未通过联机校验。", "目前方案未通過連線驗證。", "The selected build failed LAN validation.", "選択した構成はLAN検証に失敗しました。", "La configuración no superó la validación de LAN.", "Die gewählte Konfiguration hat die LAN-Prüfung nicht bestanden.", "Выбранная сборка не прошла проверку LAN."],
  privateNetwork: ["确认两机位于同一私有 IPv4 网络，并将 Windows 网络配置设为“专用”。", "確認兩機位於同一私有 IPv4 網路，並將 Windows 網路設定為「私人」。", "Keep both PCs on the same private IPv4 network and set the Windows network profile to Private.", "両PCを同じプライベートIPv4ネットワークに接続し、Windowsのネットワーク設定を「プライベート」にします。", "Conecta ambos equipos a la misma red IPv4 privada y configura el perfil de Windows como Privado.", "Verbinde beide PCs mit demselben privaten IPv4-Netz und wähle in Windows das Netzwerkprofil Privat.", "Подключите оба ПК к одной частной сети IPv4 и выберите профиль сети Windows «Частная»."],
  apIsolation: ["在路由器或无线接入点中关闭 AP / client isolation（客户端隔离）。", "在路由器或無線基地台中關閉 AP / client isolation（用戶端隔離）。", "Disable AP/client isolation on the router or wireless access point.", "ルーターやアクセスポイントのAP／クライアント分離を無効にします。", "Desactiva el aislamiento de clientes o AP en el router o punto de acceso.", "Deaktiviere AP-/Client-Isolation am Router oder WLAN-Zugangspunkt.", "Отключите изоляцию AP/клиентов на маршрутизаторе или точке доступа."],
  manualAddress: ["仍未发现时，用“手动输入 IPv4”填写房主显示的地址和端口。", "仍未發現時，在「手動輸入 IPv4」填寫房主顯示的位址和連接埠。", "If discovery stays empty, enter the host's displayed IPv4 address and port manually.", "見つからない場合は、ホストに表示されたIPv4アドレスとポートを手入力します。", "Si no aparece ninguna sala, introduce manualmente la dirección IPv4 y el puerto del anfitrión.", "Falls kein Raum erscheint, gib die angezeigte IPv4-Adresse und den Port des Hosts manuell ein.", "Если комнаты не найдены, вручную введите IPv4-адрес и порт, показанные у ведущего."],
  completeDesktop: ["从完整桌面游戏目录启动；不要单独复制 EXE。", "從完整桌面遊戲目錄啟動；不要只複製 EXE。", "Launch from the complete desktop game folder; do not copy only the EXE.", "EXEだけをコピーせず、完全なデスクトップ版フォルダーから起動します。", "Inicia el juego desde la carpeta de escritorio completa; no copies solo el EXE.", "Starte aus dem vollständigen Desktop-Spielordner; kopiere nicht nur die EXE.", "Запускайте игру из полной папки настольной версии; не копируйте только EXE."],
  firewall: ["在 Windows 防火墙中允许游戏通过专用网络；无需关闭整个防火墙。", "在 Windows 防火牆中允許遊戲通過私人網路；無須關閉整個防火牆。", "Allow the game on private networks in Windows Firewall. You do not need to disable the firewall.", "Windowsファイアウォールでゲームのプライベートネットワーク通信を許可します。全体を無効にする必要はありません。", "Permite el juego en redes privadas en el Firewall de Windows. No hace falta desactivar el firewall.", "Erlaube das Spiel in der Windows-Firewall für private Netze. Die Firewall muss nicht deaktiviert werden.", "Разрешите игре доступ к частным сетям в брандмауэре Windows. Отключать брандмауэр не нужно."],
  checkEndpoint: ["核对房主显示的 IPv4:端口（47778–47788），不要使用公网地址。", "核對房主顯示的 IPv4:連接埠（47778–47788），不要使用公網位址。", "Check the host's displayed IPv4:port (47778–47788); do not use a public address.", "ホストに表示されたIPv4:ポート（47778–47788）を確認します。公開アドレスは使用しません。", "Comprueba la IPv4:puerto del anfitrión (47778–47788); no uses una dirección pública.", "Prüfe die angezeigte IPv4:Port-Angabe des Hosts (47778–47788); verwende keine öffentliche Adresse.", "Проверьте IPv4:порт ведущего (47778–47788); не используйте публичный адрес."],
  checkVersions: ["确认两机使用相同版本及同一完整目录包。", "確認兩機使用相同版本及同一完整目錄套件。", "Use the same game version and complete folder package on both PCs.", "両PCで同じバージョンと同一の完全な配布パッケージを使用します。", "Usa la misma versión y el mismo paquete de carpeta completa en ambos equipos.", "Verwende auf beiden PCs dieselbe Version und dasselbe vollständige Ordnerpaket.", "Используйте на обоих ПК одинаковую версию и один полный пакет игры."],
  newRoom: ["请重新创建或加入新房间。本版本不支持重连或房主迁移。", "請重新建立或加入新房間。本版本不支援重新連線或房主轉移。", "Create or join a new room. This version does not support reconnection or host migration.", "新しい部屋を作成するか参加してください。このバージョンは再接続やホスト移行に対応していません。", "Crea una sala nueva o únete a otra. Esta versión no admite reconexión ni migración del anfitrión.", "Erstelle einen neuen Raum oder tritt einem bei. Diese Version unterstützt weder Wiederverbindung noch Host-Wechsel.", "Создайте новую комнату или присоединитесь к другой. Переподключение и смена ведущего не поддерживаются."],
  dismiss: ["关闭提示", "關閉提示", "Dismiss", "閉じる", "Cerrar aviso", "Hinweis schließen", "Закрыть подсказку"],
} as const satisfies Record<string, Row>;
export type LanMessageKey = keyof typeof LAN_MESSAGE_ROWS;
export const LAN_CATALOG = Object.fromEntries(SUPPORTED_GAME_LOCALES.map((locale, index) => [locale,
  Object.fromEntries(Object.entries(LAN_MESSAGE_ROWS).map(([key, row]) => [key, row[index]])),
])) as Record<GameLocale, Record<LanMessageKey, string>>;
export function lanText(locale: GameLocale, key: LanMessageKey): string { return LAN_CATALOG[locale][key]; }
